


CREATE TABLE NETFLIX_DATA
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
      FROM TABLE(
        INFER_SCHEMA(
          LOCATION=>'@DBT_DB.DBT_SCHEMA.NETFLIX_RAW_STAGE',
          FILE_FORMAT=>'CSV_NETFLIX_RAW'
        )
      ));

COPY INTO NETFLIX_DATA FROM @DBT_DB.DBT_SCHEMA.NETFLIX_RAW_STAGE
  FILE_FORMAT = (
    FORMAT_NAME= 'csv_ff'
  )