name: Run Data-Load Notebook

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

jobs:
  execute-notebook:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with: {python-version: '3.11'}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install papermill python-dotenv

   
      - name: Build .env from secrets
        run: |
          cat <<'EOF' > .env
          SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
          SNOWFLAKE_USER=${SNOWFLAKE_USER}
          SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
          SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
          SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
          EOF

      - name: Install & register ipykernel
        run: |
          pip install ipykernel                   
          python -m ipykernel install --user \
                --name python3 --display-name "Python 3"   

      - name: Create outputs directory
        run: mkdir -p outputs

      - name: Run notebook with Papermill
        run: |
          papermill \
            notebooks/snowpark_bootstrap.ipynb \
            outputs/snowpark_bootstrap-output.ipynb

      - uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: outputs/snowpark_bootstrap-output.ipynb
